import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  function questionsAskedHandler(event) {
    event.preventDefault();
    alert(event.target.question.value)
  }
  return (
    <>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='flex items-center justify-between p-4 bg-blue-200 text-black'>
        <h1 className='text-xl'>Cookie Stand Admin</h1>
      </header>
      <main className='bg-gray-200'>
        <h2 className='flex w-3/4 p-2 mx-auto my-4 bg-blue-400 justify-center rounded-lg mb-0'> Create Cookie Stand</h2>
        <form className='flex w-3/4 p-2 mx-auto my-4 bg-blue-400 rounded-lg mt-0' onSubmit={questionsAskedHandler}>
          <div className='block rounded-lg ' > 
            <div className="block p-3">
              <label className='text-xs'>Location</label>
              <input name='Location' id='input_element' 
              className='flex-auto pl-1 w-700'/>
            </div>
            <div className="p-3" id='form_questions'>
              <div className='input_boxes'>
                <label className='text-xs'>Minimum Customers per Hour</label>
                <input name='Minimum Customers per Hour' className='flex-auto pl-1' />
              </div>
              <div className='input_boxes'>
                <label className='text-xs'>Maximum Customers per Hour</label>
                <input name='Maximum Customers per Hour' className='flex-auto pl-1' />
              </div>
              <div className='input_boxes'>
                <label className='text-xs'>Average Cookies per Sale</label>
                <input name='Maximum Customers per Hour' className='flex-auto pl-1' />
              </div>
              <div>
                <button className='px-14 py-4 rounded-lg  bg-green-500 text-black '>Create</button>
              </div>
            </div>
          </div>
        </form>
        <p className='flex w-3/4 p-2 mx-auto my-4 rounded-lg justify-center'> Report Table Coming Soon...</p>
        <p className='flex justify-center'> {'{"location": "Barcelona, "minCustomers": 2, "maxCustomers":4, "avgCookies": 2.5}'} </p>
      </main>
      <footer className='p-4 mt-8 bg-blue-200 text-black'>
        <p className='text-xs'> ©2023</p>

      </footer>
    </>
  )
}
// 
